#!/usr/bin/env bash

declare -a cydia
cydia=($CYDIA)

exec 3>&1 &>/dev/null

if [ "$DPKG_MAINTSCRIPT_ARCH" == "iphoneos-arm64" ]; then
    DPKG_ROOT="/var/jb"
fi

SERV_AGENT="$DPKG_ROOT/Library/LaunchDaemons/com.82flex.trollvnc.plist"

if [ -f "$SERV_AGENT" ]; then
    launchctl unload "$SERV_AGENT" || true
else
    launchctl remove system/com.82flex.trollvnc || true
fi

sleep 2

if [ -f "$SERV_AGENT" ]; then
    launchctl load -w -F "$SERV_AGENT" || true
fi

if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}"
fi

exit 0